[workspace]
members = [
    "crates/ci-core",
    "crates/ci-python",
    "crates/ci-r/src/rust",
    "crates/ci-js",
]
resolver = "2"

[workspace.dependencies]
statrs = { version = "0.18.0"}

# Linting/development
[workspace.lints.rust]
unsafe_code = "forbid"

[workspace.lints.clippy]
all = "warn"
pedantic = "warn"

[profile.release]
lto = true
codegen-units = 1
