[package]
name = 'citest-r'
publish = false
version = '0.1.0'
edition = '2021'
rust-version = '1.81'

[workspace]
members = [ 'citest' ]
resolver = '2'

[workspace.package]
version = '0.1.0'
edition = '2021'
authors = ['GiPHouse', 'Ankur Ankan <ankurankan@gmail.com>']
license = 'MIT'
repository = 'https://github.com/pgmpy/ci-tests'

[workspace.dependencies]
statrs = { version = '0.18.0', default-features = false }

[workspace.lints.rust]
unsafe_code = 'forbid'

[workspace.lints.clippy]
all = 'warn'
pedantic = 'warn'

[lib]
crate-type = [ 'rlib', 'staticlib' ]
name = 'citestr'

[[bin]]
name = 'document'
path = 'document.rs'

[dependencies]
citest = { path = 'citest' }
extendr-api = '0.9.0'
