// Generated by extendr: Do not edit by hand
fn main() -> Result<(), Box<dyn std::error::Error>> {
    let wrapper_path =
        std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join("../../R/extendr-wrappers.R");
    let header = "\
        # Generated by extendr: Do not edit by hand\n\
        # nolint start\n\
        \n\
        #' @usage NULL\n\
        #' @useDynLib citest, .registration = TRUE\n\
        NULL\n\
        \n\
    ";
    let footer = "# nolint end\n";
    let wrappers = citestr::get_citest_metadata()
        .make_r_wrappers(true, "citest")
        .map_err(|e| format!("failed to generate wrappers: {e}"))?;
    std::fs::write(&wrapper_path, format!("{header}{wrappers}{footer}"))
        .map_err(|e| format!("failed to write {}: {e}", wrapper_path.display()))?;
    Ok(())
}
