[package]
name = "ci_js"
version = "0.1.0"
edition = "2021"
authors = ["Your Team <team@example.com>"]
license = ""
description = "wasm-pack bindings for Conditional Independence Testing"
repository = ""

[dependencies]
ci_core = { path = "../ci-core" }
ndarray = {workspace = true}

[lints]
workspace = true
