# Generated by extendr: Do not edit by hand
# nolint start

#' @usage NULL
#' @useDynLib cir, .registration = TRUE
NULL

#' Returns a sorted vector of all registered CI test names.
list_ci_tests <- function() .Call(wrap__list_ci_tests)

#' Returns a sorted vector of CI test names compatible with the given data type.
#'
#' `data_type` must be one of `"discrete"`, `"continuous"`, or `"mixed"` (case-insensitive).
#' Returns an error for any other value.
list_ci_tests_for <- function(data_type) .Call(wrap__list_ci_tests_for, data_type)

chi_squared_test <- function(x_values, y_values, z, boolean, significance_level) .Call(wrap__chi_squared_test, x_values, y_values, z, boolean, significance_level)

log_likelihood_test <- function(x_values, y_values, z, boolean, significance_level) .Call(wrap__log_likelihood_test, x_values, y_values, z, boolean, significance_level)

cressie_read_test <- function(x_values, y_values, z, boolean, significance_level) .Call(wrap__cressie_read_test, x_values, y_values, z, boolean, significance_level)

pearson_correlation_test <- function(x_values, y_values, z, boolean, significance_level) .Call(wrap__pearson_correlation_test, x_values, y_values, z, boolean, significance_level)

freeman_tukey_test <- function(x_values, y_values, z, boolean, significance_level) .Call(wrap__freeman_tukey_test, x_values, y_values, z, boolean, significance_level)

modified_likelihood_test <- function(x_values, y_values, z, boolean, significance_level) .Call(wrap__modified_likelihood_test, x_values, y_values, z, boolean, significance_level)

pearson_equivalence_test <- function(x_values, y_values, z, boolean, significance_level) .Call(wrap__pearson_equivalence_test, x_values, y_values, z, boolean, significance_level)

# nolint end
