// Golden parity test for the data-bound JavaScript / WebAssembly bindings.
//
// Loads the shared cross-language fixture `tests/fixtures/golden.json` (at the
// repository root) and, for each of the eight tests, builds a `Dataset` from the
// case's columns, constructs the test with the case's parameters, runs it, and
// asserts that `statistic` / `pValue` / `dof` match the recorded `expected`
// values within 1e-7. This is the binding's numeric parity gate against the
// scipy/pgmpy reference, mirroring the Rust (`crates/ci-core/tests/golden.rs`)
// and Python (`crates/ci-python/test/test_golden.py`) gates.

import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";
import { describe, test, expect, beforeAll } from "vitest";

// The wasm package is generated by `wasm-pack build crates/ci-js --target nodejs`
// into `crates/ci-js/pkg`. It is a CommonJS module; default-import then
// destructure so the named classes resolve regardless of interop quirks.
import pkg from "../pkg/ci_js.js";
const {
  Dataset,
  ChiSquared,
  LogLikelihood,
  CressieRead,
  FreemanTukey,
  ModifiedLikelihood,
  PearsonCorrelation,
  PearsonEquivalence,
  FisherZ,
  init,
} = pkg;

const TOL = 1e-7;
const EXPECTED_CASE_COUNT = 80;

// Map the fixture's stable test name to its binding class.
const TEST_CLASSES = {
  chi_squared: ChiSquared,
  log_likelihood: LogLikelihood,
  cressie_read: CressieRead,
  freeman_tukey: FreemanTukey,
  modified_likelihood: ModifiedLikelihood,
  pearson_correlation: PearsonCorrelation,
  pearson_equivalence: PearsonEquivalence,
  fisher_z: FisherZ,
};

const __dirname = dirname(fileURLToPath(import.meta.url));
// crates/ci-js/tests/golden.test.js -> repo root is three parents up.
const GOLDEN_PATH = resolve(__dirname, "..", "..", "..", "tests", "fixtures", "golden.json");

const GOLDEN_CASES = JSON.parse(readFileSync(GOLDEN_PATH, "utf8"));

beforeAll(() => {
  // Install the panic hook so any Rust panic surfaces as a readable JS error.
  init();
});

/** Build a `Dataset` wasm object from a fixture case's `columns`. */
function buildDataset(columns) {
  const spec = {};
  for (const [name, col] of Object.entries(columns)) {
    spec[name] = { kind: col.kind, values: col.values };
  }
  return new Dataset(spec);
}

/** Construct the test class for `name`, bound to `data`, with the case params. */
function construct(name, data, params) {
  const cls = TEST_CLASSES[name];
  if (name === "pearson_correlation" || name === "fisher_z") {
    return new cls(data);
  }
  if (name === "pearson_equivalence") {
    return new cls(data, { deltaThreshold: params.delta_threshold });
  }
  // Discrete power-divergence family: configured by `yates`.
  return new cls(data, { yates: params.yates });
}

/**
 * Assert `actual` matches `expected` for `field` within TOL. Null/undefined
 * expectations are skipped (the test does not define that field). Infinity / NaN
 * are handled exactly (none appear in the current fixture, but be defensive).
 */
function assertClose(actual, expected, field, caseId) {
  if (expected === null || expected === undefined) {
    return; // Field not defined for this test; skip.
  }
  expect(actual, `${caseId}: expected ${field}=${expected}, got ${actual}`).not.toBeNull();
  expect(actual, `${caseId}: ${field} should be defined`).not.toBeUndefined();

  const exp = Number(expected);
  if (!Number.isFinite(exp)) {
    // Infinite or NaN expectation: require an exactly-matching actual.
    if (Number.isNaN(exp)) {
      expect(Number.isNaN(actual), `${caseId}: ${field} expected NaN`).toBe(true);
    } else {
      expect(actual, `${caseId}: ${field} expected ${exp}`).toBe(exp);
    }
    return;
  }
  expect(
    Math.abs(actual - exp),
    `${caseId}: ${field} mismatch: got ${actual}, expected ${exp}`,
  ).toBeLessThanOrEqual(TOL);
}

describe("golden fixture parity", () => {
  const counts = {};

  test.each(GOLDEN_CASES.map((c, i) => [i, c]))(
    "case[%i] %o",
    (index, testCase) => {
      const caseId = `case[${index}] ${testCase.test}`;
      expect(TEST_CLASSES, `${caseId}: unknown test name`).toHaveProperty(testCase.test);

      const data = buildDataset(testCase.columns);
      const test_ = construct(testCase.test, data, testCase.params);
      const result = test_.runTest(testCase.x, testCase.y, testCase.z);
      const expected = testCase.expected;

      assertClose(result.statistic, expected.statistic, "statistic", caseId);

      // p-value: handle exact-zero defensively, otherwise compare within TOL.
      const expP = Number(expected.p_value);
      if (expP === 0.0) {
        expect(
          Math.abs(result.pValue),
          `${caseId}: pValue expected ~0, got ${result.pValue}`,
        ).toBeLessThanOrEqual(TOL);
      } else {
        assertClose(result.pValue, expP, "pValue", caseId);
      }

      assertClose(
        result.dof,
        expected.dof === null || expected.dof === undefined ? expected.dof : Number(expected.dof),
        "dof",
        caseId,
      );

      counts[testCase.test] = (counts[testCase.test] ?? 0) + 1;
    },
  );

  test("all fixture cases were exercised", () => {
    expect(GOLDEN_CASES.length).toBe(EXPECTED_CASE_COUNT);
    const names = new Set(GOLDEN_CASES.map((c) => c.test));
    expect(names).toEqual(new Set(Object.keys(TEST_CLASSES)));
  });
});
