[package]
name = "ci_python"
version = "0.1.0"
edition = "2021"
authors = ["Your Team <team@example.com>"]
license = ""
description = "PyO3 bindings for Conditional Independence Testing"
repository = ""

[dependencies]
ci_core = { path = "../ci-core" }
numpy = { version = "0.24" }
pyo3 = { version = "0.24", features = ["extension-module", "abi3-py310"] }

[lints]
workspace = true

[lib]
name = "ci_python"
crate-type = ["cdylib", "rlib"]
