[package]
name = "ci_core"
version = "0.1.0"
edition = "2021"
authors = ["Your Team <team@example.com>"]
license = ""
description = "Conditional Independence Testing"
repository = ""
keywords = ["statistics", "causal-inference", "conditional-independence"]
categories = ["science"]

exclude = [""]

[dependencies]
anyhow = { workspace = true}
ndarray = { workspace = true }
statrs = { workspace = true }
ordered-float = "5.3.0"
rand = "0.9"
nalgebra = "0.33"



[dev-dependencies]
criterion = { workspace = true }
proptest = { workspace = true }
rand_distr = "0.5"

[lints]
workspace = true

[lib]
