[package]
name = "citest-python"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
description = "PyO3 bindings for Conditional Independence Testing"
repository.workspace = true
publish = false

[dependencies]
citest = { path = "../citest" }
numpy = { version = "0.24" }
pyo3 = { version = "0.24", features = ["extension-module", "abi3-py310"] }

[lints]
workspace = true

[lib]
name = "citest_python"
crate-type = ["cdylib", "rlib"]
